blank_issues_enabled: false
contact_links:
  - name: ğŸ“š DocumentaciÃ³n
    url: https://github.com/MarxMad/CriptoUNAM-Website/blob/main/README.md
    about: Consulta la documentaciÃ³n del proyecto
  - name: ğŸ’¬ Telegram
    url: https://t.me/criptounam
    about: Ãšnete a nuestra comunidad en Telegram

